### PR TITLE
Update server.js

### PR DESCRIPTION
**Pull request by CooCooooo**
a solution to     bsonInstance = new BSON(bsonTypes);
                                               ^
                       TypeError: undefined is not a function

### CODE REVIEW

**Comment by christkv** [comment]
what os and script to reproduce. the fix you propose it's not the right one.

**Comment by CooCooooo** [comment]
I use the window8.1 and can't have the BSON compile, I work well with the change

**Comment by christkv** [comment]
it's not broken the console message you get means it could not use the c++ parser and falls back to the javascript one.

**Comment by CooCooooo** [comment]
yes, but if you can get it work for someone who don't have the c++ parser may be a good choice   ^_^

**Comment by christkv** [comment]
bumped bson to 3.0.1, delete your node_modules directory and do npm install and tell me if it fixes the issue.

**Pull request closed without merging**
