### PR TITLE
NODE-2147: Proper server topology management.

### PR DESCRIPTION
**Pull request by jduarter**
Proposed fix for NODE-2147: Unexpected behaviours using useUnifiedTopology: true
https://github.com/jduarter/mongodb-core/pull/new/NODE-2147-proper-server-topology-management

### CODE REVIEW

**Comment by millerick** [comment]
@mbroadst , should this be submitted to https://github.com/mongodb/node-mongodb-native ?

**Comment by mbroadst** [comment]
@millerick yes, this repo is no longer actively developed. Having said that, I'm in the process of writing documentation explaining why we made the decision not to export a number of these events, and the paradigm shifts we intend to introduce with the new topology layer. I'll be following up in the jira ticket, and we can discuss there.

**Comment by jduarter** [comment]
Thanks for your response @mbroadst , in that case I'm going to close this request. Really looking forward to it, thanks for your response!

**Comment by cjcheshire** [comment]
👋 was keeping an eye on this PR as we’ve encountered this issue in prod. Is the jira ticket public?

**Comment by letsgolesco** [comment]
> 👋 was keeping an eye on this PR as we’ve encountered this issue in prod. Is the jira ticket public?

@cjcheshire this may be the jira ticket you're looking for: https://jira.mongodb.org/browse/NODE-2147

**Comment by mbroadst** [comment]
@cjcheshire sorry! The ticket number was in the branch name for this patch, I stupidly assumed that was obvious :man_facepalming: Yes, [NODE-2147](https://jira.mongodb.org/browse/NODE-2147) is the ticket to track. I'll hopefully have detailed notes for all of your by Wednesday this week, apologies for the delay.

**Comment by cjcheshire** [comment]
@mbroadst thank you for the update! 🙂

**Pull request closed without merging**
